
name: Mark stale issues and pull requests

on:
  schedule:
  #Cron is the time the action takes place the first number being minutes the second is hours
  #So in this case 6PM (timezone is utc)
  - cron: '00 17 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Stale issue message'
        stale-pr-message: 'Stale pull request message'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
